# version: '3'
# services:
#   backend:
#     networks: [scheduler-network]
#     build: .
#     ports:
#      - 8080:8080
#     volumes:
#      - .:/usr/src/app
#      - /usr/src/app/node_modules

#   scheduler-pgadmin:
#     networks: [scheduler-network]
#     container_name: scheduler-app-db-pgadmin
#     image: dpage/pgadmin4:4.21
#     environment:
#       PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
#       PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
#     volumes:
#       - scheduler-app-pgadmin:/var/lib/pgadmin
#     ports:
#       - '${PGADMIN_PORT:-9693}:80'
#     restart: unless-stopped

# volumes:
#   scheduler-app-pgadmin:

# networks:
#   scheduler-network:
